project_id = "oxvpukidtudltzntwlsz"

[functions.reset-admin-password]
verify_jwt = true

[functions.create-test-funeraria]
verify_jwt = true

[functions.create-care-checkout]
verify_jwt = true

[functions.care-customer-portal]
verify_jwt = true

[functions.care-stripe-webhook]
verify_jwt = false

[functions.check-care-subscription]
verify_jwt = true

[functions.create-technician]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false

[functions.register-funeraria]
verify_jwt = false

[functions.notify-funeraria-activation]
verify_jwt = true