
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/07-joao-carlos-de-brito-galvao.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Brito Galv%';
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/08-lourenco-goncalves-cunha.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Gon%alves Cunha%';
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/09-maria-monteiro-pereira.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Monteiro Pereira%';
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/10-antonio-de-morais-correa.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Morais Corr%';
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/11-maria-pereira-dantas.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Pereira Dantas%';
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/12-antonio-alberto-dias.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Alberto Dias%';
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/13-olinda-esteves-loureiro.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Esteves Loureiro%';
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/14-maria-da-conceicao-lopes-pereira-rodrigues.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Concei%Lopes%Rodrigues%';
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/15-amaro-martins-de-barros.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Martins de Barros%';
UPDATE obituaries SET photo_url = 'https://oxvpukidtudltzntwlsz.supabase.co/storage/v1/object/public/obituary-photos/sjoao-import/16-armando-silva-araujo.jpg' WHERE funeraria_id = '1dd8e1e1-2c91-49f9-a1b0-1faa7dc4b55d' AND display_name ILIKE '%Silva Ara%jo%';
